
# This file contains the configuration for Supabase Functions

project_id = "tyqmfhtfvrffkaqttbcf"

[functions.generate-strava-auth-url]
verify_jwt = true

[functions.strava-auth]
verify_jwt = true

[functions.save-strava-token]
verify_jwt = true

[functions.refresh-strava-token]
verify_jwt = true

[functions.get-strava-gear]
verify_jwt = true

[functions.verify-wordpress-premium]
verify_jwt = true

[functions.check-wordpress-user]
verify_jwt = false
