
project_id = "tyqmfhtfvrffkaqttbcf"

[api]
enabled = true

[db]
enabled = true

[realtime]
enabled = true
wal_level = "logical"

[studio]
enabled = true

[auth]
enabled = true

[storage]
enabled = true

[functions]
[functions.save-strava-token]
verify_jwt = true

[functions.refresh-strava-token]
verify_jwt = true

[functions.get-strava-gear]
verify_jwt = true

[functions.strava-auth]
verify_jwt = true
