
const enCalendar = {
  "calendar": "Calendar",
  "loading": "Loading...",
  "no_bikes": "No bikes available",
  "create_bike_first": "You need to create at least one bike first",
  "bike": "Bike",
  "maintenance": "Maintenance",
  "scheduled_appointment": "Scheduled appointment",
  "maintenance_alert": "Maintenance alert",
  "no_events_for_day": "No events scheduled for this day",
  "appointment": "Appointment",
  "alert": "Alert",
  "no_upcoming_appointments": "No upcoming appointments",
  "every_distance": "Every {distance} km",
  "every_months": "Every {months} months",
  "complete": "Complete",
  "delete": "Delete",
  "no_active_alerts": "No active alerts",
  "configure_alerts_from_bikes": "Configure automatic alerts from each bike's page",
  "add": "Add",
  "select_bike": "Select a bike",
  "choose_bike_for_appointment": "Choose the bike for which you want to create an appointment or maintenance alert.",
  "pending": "Pending",
  "requires_attention": "Requires attention",
  "automatic": "automatic",
  "alert_deleted": "Alert deleted",
  "alert_deleted_desc": "The maintenance alert has been successfully deleted",
  "alert_delete_error": "Could not delete alert",
  "maintenance_recorded": "Maintenance recorded",
  "maintenance_alert_completed": "Maintenance registered and alert deactivated",
  "operation_failed": "Could not complete the operation",
  "automatic_maintenance_alert": "Automatic maintenance from alert",
  "type": "Type",
  "alerts": "Alerts",
  "maintenance_plan": "Maintenance Plan",
};

export default enCalendar;
