
const enUiMaintenance = {
  "add_maintenance_dialog_title": "Add Maintenance",
  "new_maintenance_type": "New maintenance type",
  "new_type_name_placeholder": "Name of new type",
  "maintenance_type": "Maintenance type",
  "cant_find_type_title": "Can't find the type you need?",
  "cant_find_type_desc": "You can create a custom type by clicking the + button next to the selector.",
  "add_new_type": "Add new type",
  "current_mileage": "Current mileage",
  "strava_distance_desc": "The distance will update automatically from Strava when the date changes",
  "labor_cost": "Labor (€)",
  "materials_cost": "Materials (€)",
  "date": "Date",
  "notes": "Notes",
  "additional_notes_placeholder": "Additional notes",
  "schedule_appointment": "Schedule next appointment",
  "additional_notes": "Additional notes",
  "notes_placeholder": "Workshop, type of repair, etc.",
  "search_repair_type": "Search by repair type",
  "search_repair_type_placeholder": "Search for repair type...",
  "repair_type": "Repair type",
  "category": "Category",
  "quantity": "Quantity",
  "total_cost": "Total Cost",
  "custom": "Custom",
  "no_results_found": "No results found",
  "last_service": "Last Service",
  "custom_maintenance_required": "Please enter a custom maintenance type",
};

export default enUiMaintenance;
